# Generated by Django 4.0.2 on 2022-03-21 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_postinstance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postinstance',
            unique_together={('post', 'starrer')},
        ),
    ]
